### ISSUE TITLE
feat: Automate Issue Closure on Move to 'Done' in Project Board

### ISSUE THREAD

**Issue by loftwah** [ImLunaHey/screenshot#16]
**Summary:**
Develop a mechanism to automatically close issues when they are moved to the 'Done' column in our GitHub project boards. This feature aims to streamline our workflow and ensure that our issue tracking accurately reflects the current state of tasks.

**Problem:**
Currently, issues need to be manually closed after they are moved to the 'Done' column on our project boards. This manual step can lead to discrepancies between the project board's state and the actual issue status, potentially causing confusion and miscommunication among team members.

**Proposed Solution:**
Implement a GitHub Action or use an existing GitHub integration that triggers when an issue is moved to the 'Done' column in any of our project boards. Once triggered, the action should automatically change the issue's status to closed.

**Benefits:**
- Enhances workflow efficiency by reducing manual steps.
- Keeps project boards and issue statuses in sync, improving project management and visibility.
- Reduces the chances of overlooked issues that have been completed but not closed.

**Implementation Notes:**
- Investigate GitHub Actions or third-party GitHub Apps that offer project board automation features.
- Ensure that the automation is configurable so that it can be adapted or disabled for specific scenarios where manual issue closure is preferred.
- Test the automation in a controlled environment to ensure it does not inadvertently close issues that are moved to 'Done' prematurely.

This feature is crucial for maintaining a clean and efficient project management process, ensuring that our GitHub project boards accurately reflect the real-time progress of our tasks.

**Comment by loftwah** [comment]
Here's a basic outline of steps you'd follow to set this up:

1. **Create a GitHub Action Workflow**: You need to create a new GitHub Action in your repository by adding a YAML file to the `.github/workflows` directory. This action will listen for `project_card` events.

2. **Specify the Trigger Event**: Use the `project_card` event trigger and specify the types you're interested in, likely `moved`.

3. **Check the Column**: The action script should check if the moved card is now in the "Done" column. This might require fetching additional details about the column via the GitHub API because the `project_card` event payload includes the card's URL but not its direct column name or ID.

4. **Close the Issue**: If the card is in the "Done" column, use the GitHub API to close the associated issue. You'll likely need to extract the issue number from the project card's content URL.

Here is an example of a GitHub Action workflow that outlines these steps. Note that this example is conceptual and requires customization, especially for step 3, where you need to determine the correct column:

```yaml
name: Auto Close Issue When Moved to Done

on:
  project_card:
    types: [moved]

jobs:
  auto-close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch card details
        id: card_details
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const card = await github.rest.projects.getCard({
              card_id: ${{ github.event.project_card.id }}
            });
            return card;

      # Add your logic here to check if the card is in the "Done" column
      # This is a simplified placeholder and will not work as-is
      - name: Close associated issue if in Done column
        if: steps.card_details.outputs.column_name == 'Done'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = extractIssueNumberFromCard(steps.card_details.outputs.card); // You need to implement extractIssueNumberFromCard
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              state: 'closed'
            });
```

This script needs additional implementation details, particularly in how you determine if a card is in the "Done" column and how to extract the issue number from the project card's content URL.

Automating board and issue management through GitHub Actions can be very powerful, but it often requires a good understanding of both the GitHub Actions platform and the GitHub API. For more detailed and complex workflows, you may need to write custom scripts or use third-party GitHub Actions from the Marketplace that suit your specific needs.
